spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    default: dev

sentry:
  dsn: ${SENTRY_DSN:}
  # Add data like request headers and IP for users,
  # see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
  send-default-pii: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem